services:
  - type: static
    name: my-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_ENDPOINT
        value: https://blog-back-yd1w.onrender.com
